name: Release application

on:
  push:
    branches: [ main ]
    tags: ['*']

env:
  BRANCH: ${{ github.ref_name }}
  GITHUB_SHA: ${{ github.sha }}

jobs:
  build-and-publish:
    name: Build & Publish to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: main 
          fetch-depth: 0
      
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3
      
      - name: 'Build and push "todo-app"'
        uses: docker/build-push-action@v6
        with:
          context: ./project/todo-app
          file: ./project/todo-app/Dockerfile
          push: true
          tags: "lucksei/todo-app:${{ env.BRANCH }}-${{ env.GITHUB_SHA }}"
      
      - name: 'Build and push "todo-backend"'
        uses: docker/build-push-action@v6
        with:
          context: ./project/todo-backend
          file: ./project/todo-backend/Dockerfile
          push: true
          tags: "lucksei/todo-backend:${{ env.BRANCH }}-${{ env.GITHUB_SHA }}"
      
      - name: 'Build and push "todo-broadcaster"'
        uses: docker/build-push-action@v6
        with:
          context: ./project/todo-broadcaster
          file: ./project/todo-broadcaster/Dockerfile
          push: true
          tags: "lucksei/todo-broadcaster:${{ env.BRANCH }}-${{ env.GITHUB_SHA }}"